export const ChordType = {
  Major: "Major",
  Seventh: "Seventh",
  MajorSeventh: "MajorSeventh",
  Sixth: "Sixth",
  Minor: "Minor",
  MinorSeventh: "MinorSeventh",
  MinorMajor: "MinorMajor",
  MinorSixth: "MinorSixth",
  SuspendedSecond: "SuspendedSecond",
  SuspendedFourth: "SuspendedFourth",
  SeventhSuspendedSecond: "SeventhSuspendedSecond",
  SeventhSuspendedFourth: "SeventhSuspendedFourth",
  Diminished: "Diminished",
  Augmented: "Augmented",
  Power: "Power",
} as const;
